### ISSUE TITLE
Feat. Request: Share audio

### ISSUE THREAD

**Issue by igorcafe** [muzam1l/mooz#4] opened 2021-09-22 00:04 UTC
Meet has this feature when you share a specific tab on Linux, and I believe you can share output sound on Windows too.

**Comment by muzam1l** [comment] 2021-09-22 08:16
So yeah, audio in screen sharing was not set, can you test this to see if it meets your needs.
 
https://deploy-preview-5--mooz-app.netlify.app

**Comment by muzam1l** [comment] 2021-09-27 16:17
I am on Windows, and this deploy preview shows option for Tab audio like this.

![image](https://user-images.githubusercontent.com/52374648/134946498-480e15d9-9d03-4d5b-b392-bb70db87ffe3.png)

Can you share the screenshots or additional details, how it shows on your machine.

**Comment by resetcoder** [comment] 2022-02-05 04:39
I had the same issue and I found that [this clause in /src/utils/hooks/use-streams.tsx](https://github.com/muzam1l/mooz/blob/0ec764be4ee5892105589afb76bd8e9abc6d377e/src/utils/hooks/use-streams.tsx#L211) didn't have the attribute for audio, so I changed it to:

```
            const stream = await (navigator.mediaDevices as any).getDisplayMedia({
                video: { cursor: 'always' },
                audio: true
            })
```
Now I have the "Share system audio" or "Share tab audio" checkboxes on the sharing window, but I still don't think audiostream goes through.

I'm not familiar with this code, but as I see screen/window/tab sharing is used as a media device and if I add the `audio: true` attribute then it should attach audio to the stream object. The only I can think of is somewhere where this stream object is processed the audio track is simply isn't attached to the routing to the clients. Any idea?

**Comment by muzam1l** [comment] 2022-02-05 09:07
Yep, now I remember, screen share audio track is "unhandled" by design.

Basically managing tracks in peer connection is kinda ugly here, so how I go about it is removing audio track entirely if you say mute and add it back if you unmute instead of just, you know, muting and unmuting it (`enabled` fields to be precise) :).

Correctly handling more than one audio or more than one video gets ugly in peer to peer. Getting even addition video track is handled trickily, all dirty code in this [file](https://github.com/muzam1l/mooz/blob/master/src/app/connections/peer.tsx). Therefore stream audio is not here for now!

**Comment by resetcoder** [comment] 2022-02-05 09:15
But I just don't get it, if the screen capture is just a stream, then why not just distribute it as is to all the clients, and if you already showing the stream in a video player element at client side, it can play both the video and audio for everyone. If the client who shares the screen doesn't tick the checkbox "share audio", then the stream simply won't have audio track, therefore will be mute.

I think the audio sharing problem could be resolved by not removing the audio track from the stream, and the client who is sharing can decide if audio is shared or not.

I'm totally not familiar how these things work, tell me if I'm wrong.

**Comment by muzam1l** [comment] 2022-02-05 09:32
Yes you can send the multiple tracks of audio and video in peer connection. However they do not have deterministic id or anyway to differentiate between two audio and video tracks, so no information for even cleaning up some old "dead" tracks. That's why I send new track instead of muting-unmuting the existing track so other client can just destroy previous tracks and use new ones, that's unfortunate and getting even addition video track is just hacky. 

Well additional audio can be made to work with similar hacks even in current setup, but it's just peer connection api is so shitty that I don't want to deal with it just now.

**Comment by resetcoder** [comment] 2022-02-05 09:44
I see. I'm not familiar with this kind of js, I don't know how the peer handling works, I thought you handle each data packet yourself, that could make things much simpler, if you can just add a metadata to each packet what is what. If it is a built-in stuff, then I understand you have to "hack" your solution into it, that's not ideal.

I wanted to use this application to a web meeting and it works very well, except the audio sharing. I had to do a workaround to mix the desktop audio with the microphone in a [virtual audio device](https://vb-audio.com/Voicemeeter/potato.htm) and use it as my microphone, that worked.

So I understand the issue now and give up hacking in the audio sharing. Thanks anyways! Nice little app, though.

**Comment by muzam1l** [comment] 2022-02-05 09:49
That's the issue, you can send metadata as seprate data channel, but media tracks do not even have same Id across connection, so you don't have any information on recieving tracks.

And glad that you liked it, thanks.

**Comment by muzam1l** [comment] 2023-08-02 20:37
A little update on this. I rewrote the whole app logic and many things should make sense now! So Tab audio can now be shared wherever the browser allows it in https://github.com/muzam1l/mooz/pull/16. 

You can check the preview at [here](https://deploy-preview-16--mooz-app.netlify.app). There may still be bugs on that branch as it is still in early development and not thoroughly tested and many things need improvements. But it is still a huge step up from the last version.

**Closed as completed** 2023-08-04 18:00 UTC
